name: hs-hath
version: 1.0.0
github: "pe200012/hs-hath"
license: GPL-3
author: "pe200012"
maintainer: "1326263755@qq.com"
copyright: "2024 pe200012"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: A Haskell implementation of the Hath client
category: Web

description: Please see the README on GitHub at <https://github.com/pe200012/hs-hath#readme>

language: GHC2021

tested-with:
  - GHC == 9.6.6

dependencies:
  - base >= 4.7 && < 4.22
  - aeson >= 2.1 && < 2.3
  - async >= 2.2 && < 2.3
  - base64 >= 1.0 && < 1.1
  - bytestring >= 0.11 && < 0.13
  - binary >= 0.8 && < 0.9
  - co-log-core >= 0.3 && < 0.4
  - co-log >= 0.6 && < 0.8
  - co-log-polysemy >= 0.0.1.5 && < 0.0.2
  - containers >= 0.6 && < 0.8
  - cryptostore >= 0.3 && < 0.4
  - crypton >= 1.0 && < 1.1
  - crypton-connection >= 0.4 && < 0.5
  - crypton-x509 >= 1.7 && < 1.8
  - crypton-x509-store >= 1.6 && < 1.7
  - directory >= 1.3 && < 1.4
  - dhall >= 1.42 && < 1.43
  - sqlite-simple >= 0.4 && < 0.5
  - extra >= 1.7 && < 1.9
  - exceptions >= 0.10 && < 0.11
  - hex-text >= 0.1 && < 0.2
  - safe-exceptions >= 0.1 && < 0.2
  - string-interpolate >= 0.3 && < 0.4
  - servant >= 0.20.2 && < 0.21
  - servant-server >= 0.20.2 && < 0.21
  - servant-client >= 0.20.2 && < 0.21
  - servant-client-core >= 0.20.2 && < 0.21
  - http-client >= 0.7 && < 0.8
  - http-client-tls >= 0.3 && < 0.4
  - http-conduit >= 2.3 && < 2.4
  - http-types >= 0.12 && < 0.13
  - http-media >= 0.8 && < 0.9
  - lrucache >= 1.2 && < 1.3
  - monad-control >= 1.0 && < 1.1
  - monad-loops >= 0.4 && < 0.5
  - network >= 3.1 && < 3.3
  - mtl >= 2.3 && < 2.4
  - memory >= 0.18 && < 0.19
  - optparse-applicative >= 0.18 && < 0.19
  - placeholder >= 0 && < 1
  - polysemy >= 1.9 && < 1.10
  - polysemy-zoo >= 0.8 && < 0.9
  - prometheus >= 2.3.0 && < 2.4
  - process >= 1.6 && < 1.7
  - template-haskell >= 2.19 && < 2.24
  - filepath >= 1.4 && < 1.6
  - suspend >= 0.2 && < 0.3
  - text >= 2.0 && < 2.2
  - time >= 1.12 && < 1.15
  - transformers >= 0.6 && < 0.7
  - tls >= 2.0 && < 2.2
  - tls-session-manager >= 0.0.5 && < 0.1
  - timers >= 0.2 && < 0.3
  - relude >= 1.2 && < 1.3
  - stm >= 2.5 && < 2.6
  - unix >= 2.8 && < 2.9
  - unordered-containers >= 0.2 && < 0.3
  - unliftio >= 0.2 && < 0.3
  - wai >= 3.2 && < 3.3
  - wai-extra >= 3.1 && < 3.2
  - warp >= 3.4 && < 3.5
  - warp-tls >= 3.4 && < 3.5
  - minio-hs >= 1.7 && < 1.8
  - conduit >= 1.3 && < 1.4
  - resourcet >= 1.3 && < 1.4

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2
#  - -static
#  - -optl-static

default-extensions:
  - NoImplicitPrelude
  - TypeApplications
  - OverloadedStrings
  - ScopedTypeVariables
  - QuasiQuotes
  - LambdaCase
  - ViewPatterns
  - MultiParamTypeClasses
  - GADTs

library:
  source-dirs: src

executables:
  hs-hath:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fpedantic-bottoms
    dependencies:
      - hs-hath

  migrate-to-r2:
    main: Migrate.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - Migrate
    dependencies:
      - hs-hath
      - optparse-applicative
      - directory

tests:
  hs-hath-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hs-hath
      - hspec >= 2.11 && < 2.12
      - warp >= 3.4 && < 3.5
      - http-types >= 0.12 && < 0.13
      - wai >= 3.2 && < 3.3
      - http-client >= 0.7 && < 0.8
      - stm >= 2.5 && < 2.6
      - unordered-containers >= 0.2 && < 0.3
      - string-interpolate >= 0.3 && < 0.4
      - text >= 2.0 && < 2.2
      - bytestring >= 0.11 && < 0.13
