resolver: lts-24.27
compiler: ghc-9.12.2

packages:
  - .

extra-deps:
  - polysemy-zoo-0.8.2.0
  - suspend-0.2.0.0
  - timers-0.2.0.4
  - cryptostore-0.3.0.1
  - vendor/placeholder

allow-newer: true
allow-newer-deps:
  - polysemy-zoo

flags:
  cryptostore:
    use_crypton: True

nix:
  enable: false
