resolver: lts-24.27
compiler: ghc-9.12.2

packages:
  - .

extra-deps:
  - suspend-0.2.0.0
  - timers-0.2.0.4
  - cryptostore-0.3.0.1
  - time-units-1.0.0
  - ini-0.4.2
  - digest-0.0.2.1
  - mason-0.2.6
  - random-1.3.1

allow-newer: true
allow-newer-deps:
  - mason

flags:
  cryptostore:
    use_crypton: True

nix:
  enable: false
