resolver: lts-22.28

packages:
  - .

extra-deps:
  - Cabal-3.10.3.0
  - Cabal-syntax-3.10.3.0
  - cryptostore-0.3.0.1
  - base64-1.0
  - bytestring-0.11.5.3
  - binary-0.8.9.2
  - directory-1.3.8.4
  - filepath-1.4.300.2
  - haskeline-0.8.2.1
  - parsec-3.1.17.0
  - process-1.6.20.0
  - text-2.0.2
  - unix-2.8.5.1
  - containers-0.6.8
  - crypton-1.0.0
  - crypton-connection-0.4.0
  - network-3.1.4.0
  - time-1.12.2
  - tls-2.0.5
  - tls-session-manager-0.0.5
  - crypto-token-0.1.1
  - warp-3.4.1
  - auto-update-0.2.0
  - http2-5.2.2
  - time-manager-0.1.0
  - http-semantics-0.0.1
  - network-control-0.1.0
  - polysemy-zoo-0.8.2.0
  - placeholder-0
  - servant-0.20.2
  - servant-client-0.20.2
  - servant-client-core-0.20.2
  - servant-server-0.20.2
  - timers-0.2.0.4
  - suspend-0.2.0.0

allow-newer: true
allow-newer-deps:
  - polysemy-zoo

flags:
  cryptostore:
    use_crypton: True
